import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'
const roboto = Roboto_Mono({
	weight: ['200', '300', '400', '500', '600', '700'],
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Tsukurou',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<meta name='google-site-verification' content='eoTkLD9BkXvY8XVLcSG1bzBr8wMwK9Z84TE4tJactUY' />
			<head>
				<meta name='viewport' content='width=device-width, initial-scale=1.0, viewport-fit=cover' />
			</head>
			<body className={`${roboto.className} antialiased min-h-screen`} suppressHydrationWarning>
				{children}
				<Toaster position='top-right' richColors />
				<SpeedInsights />
			</body>
		</html>
	)
}
