import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const roboto = Roboto_Mono({
	weight: ['200', '300', '400', '500', '600', '700'],
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Tsukurou',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.className} antialiased h-svh`} suppressHydrationWarning>
				{children}
				<Toaster position='top-right' richColors />
			</body>
		</html>
	)
}
