import {
	BadgePlusIcon,
	BellDot,
	BookCopy,
	BookHeart,
	BookOpenText,
	Brain,
	ChartColumnDecreasing,
	FileUser,
	HelpCircle,
	House,
	ListCheck,
	LogOut,
	Settings,
	Users,
} from 'lucide-react'

export const navbarIconMap = {
	books: <BookCopy className={'max-sm:size-5'} />,
	brain: <Brain className={'max-sm:size-5'} />,
	home: <House className={'max-sm:size-5'} />,
	badge: <BadgePlusIcon className={'max-sm:size-5'} />,
	bookHeart: <BookHeart className={'max-sm:size-5'} />,
	listCheck: <ListCheck className={'max-sm:size-5'} />,
	users: <Users className={'max-sm:size-5'} />,
	bell: <BellDot className={'max-sm:size-5'} />,
	settings: <Settings className={'max-sm:size-5'} />,
	help: <HelpCircle className={'max-sm:size-5'} />,
	logout: <LogOut className={'max-sm:size-5'} />,
	FileUser: <FileUser className={'max-sm:size-5'} />,
	reading: <BookOpenText className={'max-sm:size-5'} />,
	ChartColumnDecreasing: <ChartColumnDecreasing className={'max-sm:size-5'} />,
} as const
